#!/usr/bin/env bash

if [ ! -z "$DEBUG" ]; then
  env
  set -x
fi

# If running from an extracted image, then export $0 as ARGV0
if [ -z "${APPIMAGE}" ]; then
  ARGV0="$0"
fi

export ARGV0
export CMD_GIVEN="$0"
export CMD_BASE=$(basename "${ARGV0}") # command given
export CMD_ARGS="$@"

SELF=$(readlink -f -- "$0") # current path to AppRun
HERE=${SELF%/*}             # current directory of AppRun

export APPDIR="${APPDIR:-${HERE}}"

export PATH="${HERE}/usr/local/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/local/lib:${HERE}/usr/lib/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export CFLAGS="-I${HERE}/usr/local/include -I${HERE}/usr/local/include/openssl -I${HERE}/usr/local/include/python3.10d${CFLAGS:+ $CFLAGS}"
export LDFLAGS="-L${HERE}/usr/local/lib -L${HERE}/usr/local/lib/python3.10${LDFLAGS:+ $LDFLAGS}"

if [[ "${CMD_BASE}" =~ .*(python|AppRun).* ]]; then
  exec $APPDIR/usr/local/bin/python3.10 "$@"
else
  exec $APPDIR/usr/local/bin/$CMD_BASE "$@"
fi
